name: djibrider
description: DjibRide mobile app for passenger and driver
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  google_maps_flutter: ^2.2.5
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  flutter_secure_storage: ^7.0.1
  equatable: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
